<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Berries.cs" />
    <Compile Remove="Food.cs" />
    <Compile Remove="Meat.cs" />
    <Compile Remove="Resource1.cs" />
    <Compile Remove="Resourses.cs" />
    <Compile Remove="Wood.cs" />
  </ItemGroup>

</Project>
